### ISSUE TITLE
warnings on extension from about:debugging page

### ISSUE THREAD

**Issue by goutham2688** [aaronraimist/DontFuckWithPaste#15]
hey,
thanks for the extension, 
I saw some not supported warnings on about:debugging page in firefox.
not sure if this is a issue or not. for me the extension seems to be working without issue.

attached the screenshot of the issue.

![DFP](https://user-images.githubusercontent.com/12175784/118299828-3ff17f80-b4af-11eb-9922-d447ccc6edbc.png)

**Comment by aaronraimist** [comment]
@goutham2688 Interesting. I don't see that warning. What version of Firefox is that?

**Comment by goutham2688** [comment]
on WIndows 10 machine, FireFox version 88.0.1 (64-bit)

**Comment by aaronraimist** [comment]
I'm not sure why I don't see the warning but I guess Firefox only supports having the background script be persistent. The extension doesn't mind if they are unloaded and recreated which is why persistent is set to false. It should still work fine with it being persistent. It just means it will use a bit more memory than running the addon in Chrome.

**Comment by goutham2688** [comment]
cool, as mentioned I don't see any difference in the working of the extension.
i'll close the issue for now then?

**Comment by aaronraimist** [comment]
Yeah I'll close it
