### ISSUE TITLE
Fails on github

### ISSUE THREAD

**Issue by mrx23dot** [aaronraimist/DontFuckWithPaste#21]
When you try to delete a repo on github it asks you to type in repo name, but you cannot copy it from text.
So this addon doesn't help there.

**Comment by aaronraimist** [comment]
You can copy it from here.
<img width="491" src="https://user-images.githubusercontent.com/5855073/231906236-e66bc5a5-2a47-40cf-94a8-54690280d208.png">

**Comment by mrx23dot** [comment]
Fare enough, but why doesnt it work from the "To confirm" line? 
Other websites might use that method.

**Comment by aaronraimist** [comment]
This extension is only designed to keep websites from preventing you from pasting text.

This issue is out of scope since GitHub is not preventing you from pasting text. GitHub is preventing you from selecting text. Other extensions like https://addons.mozilla.org/en-US/firefox/addon/enable-copy-by-gary/ can help with that.

**Comment by mrx23dot** [comment]
Ok, so there is a market gap to have select/copy/paste in one addon :)
