### ISSUE TITLE
Ally.com

### ISSUE THREAD

**Issue by insevin** [aaronraimist/DontFuckWithPaste#4]
Tried to paste a dollar amount into a bank transfer screen on secure.ally.com. Nothing happened, so I added & saved the addon rule for the site. Still did not work. Tried pasting random text from URL bar to the field on ally, no result. I have added rules maybe 5-6 times in the last month or so and this is the first time it has failed.

**Comment by insevin** [comment]
If there is any info I can pull like the source html of the page, let me know.

**Comment by aaronraimist** [comment]
I can confirm your issue in both Firefox and Chrome but unfortunately this Firefox version of the add-on is just following the upstream Chrome implementation. I am just maintaining the add-on so it works in Firefox. Since this isn't a Firefox specific issue I would recommend that you open up an issue here: https://github.com/jswanner/DontFuckWithPaste/issues.
